import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'

import { Space_Mono as Font } from 'next/font/google'
import './globals.css'

import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes';
import { primary } from '@/tailwind.config';
const font = Font({ weight: "400", subsets: ["latin"], display: "swap" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={font.className}>
      <head>
        <script async src="https://js.stripe.com/v3/pricing-table.js"></script>
      </head>
      <ClerkProvider appearance={{
        variables: { colorPrimary: primary[600], fontFamily: font.style.fontFamily, fontSize: "24px" },
      }}>
        <body className={font.className + "bg-gradient-to-t from-pink-500 via-red-500 to-yellow-500   text-black   "}>{children}</body>
      </ClerkProvider>
    </html>
  )
}
