import Markdown from "react-markdown"

const TermsOfService = () => {
  const terms = `# Terms of Service for Magic AI Articles

  *Last Updated: 02/04/2024*
  
  Welcome to **Magic AI Articles**! We are thrilled to have you as a user of our AI-powered SaaS platform. Before you commence using our services, please carefully read and understand the following terms and conditions:
  
  ## 1. Acceptance of Terms
  
  By accessing or using Magic AI Articles's services, you agree to comply with and be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our services.
  
  ## 2. Description of Services
  
  Magic AI Articles provides a SaaS platform that utilizes artificial intelligence to generate blog articles based on user input and preferences. The generated content is customizable and can be edited by users to meet their specific needs.
  
  ## 3. User Accounts and Security
  
  To access certain features of our services, you may be required to create an account. You are responsible for maintaining the confidentiality of your account credentials and ensuring the security of your account. You agree to notify us immediately of any unauthorized use or security breach.
  
  ## 4. User Responsibilities
  
  - You agree to use our services in compliance with all applicable laws and regulations.
  - You are solely responsible for the content generated using our platform, and you must ensure that it complies with copyright, trademark, and other intellectual property laws.
  - You agree not to use our services for any illegal or unauthorized purpose.
  
  ## 5. Intellectual Property
  
  All intellectual property rights related to our services, including but not limited to software, algorithms, and content, are owned or licensed by Magic AI Articles. You may not use, reproduce, or distribute any part of our services without our express written permission.
  
  ## 6. Privacy and Data Security
  
  We take your privacy seriously. Our [Privacy Policy](#), available on our website, outlines how we collect, use, and protect your personal information. By using our services, you agree to the terms of our Privacy Policy.
  
  ## 7. Subscription and Payment
  
  If you subscribe to our premium services, you agree to pay the applicable fees as outlined on our website. Payments are non-refundable, and your subscription will automatically renew unless you cancel it before the renewal date.
  
  ## 8. Termination
  
  We reserve the right to terminate or suspend your account and access to our services at our discretion, without prior notice, for any reason, including but not limited to a breach of these Terms of Service.
  
  ## 9. Disclaimer of Warranty
  
  Our services are provided "as is," without any warranties, either express or implied. We do not guarantee the accuracy, completeness, or suitability of the content generated by our platform.
  
  ## 10. Limitation of Liability
  
  In no event shall Magic AI Articles be liable for any indirect, incidental, special, or consequential damages arising out of or in any way connected with the use of our services.
  
  ## 11. Governing Law
  
  These Terms of Service are governed by and construed in accordance with the laws of Florida, United States. Any disputes arising from or in connection with these terms shall be resolved through arbitration in accordance with the rules of the American Arbitration Association, and judgment upon the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof.
  
  ## 12. Changes to Terms
  
  We reserve the right to modify or revise these Terms of Service at any time. You will be notified of significant changes, and your continued use of our services after such changes constitutes your acceptance of the updated terms.
  
  If you have any questions or concerns about these Terms of Service, please contact us at [support@magicaiarticles.com](mailto:support@magicaiarticles.com).
  
  Thank you for choosing Magic AI Articles!
  
  ## 13. Limitation of Liability for Damages
  
  In no event shall Magic AI Articles be liable for any direct, indirect, incidental, consequential, or special damages, including but not limited to damages for loss of profits, data, or other intangible losses, arising out of or in connection with the use or inability to use our services.
  
  ## 14. Force Majeure
  
  Magic AI Articles shall not be liable for any failure or delay in the performance of its obligations hereunder arising out of or caused by circumstances beyond its reasonable control, including, but not limited to, acts of God, acts of terrorism, fire, flood, pandemic, or other unforeseen circumstances.
  
  ## 15. Indemnification
  
  The user agrees to indemnify and hold Magic AI Articles harmless from any claim, demand, or damage, including reasonable attorneys' fees, arising out of or in connection with their use of the services, violation of these Terms of Service, or infringement of any intellectual property or other rights of any person or entity.
   `
  return (
    <div className="px-16 py-4 bg-white prose  *:text-black  prose-strong:text-black">

      <Markdown>
        {terms}
      </Markdown>
    </div>
  )
}

export default TermsOfService