const topicsArray = [
  "Quantum Physics",
  "Sustainable Energy",
  "Machine Learning",
  "Human Psychology",
  "Artificial Intelligence",
  "Climate Change",
  "Genetic Engineering",
  "Ancient History",
  "Cybersecurity Threats",
  "Space Exploration",
  "Renewable Resources",
  "Digital Marketing Trends",
  "Cultural Diversity",
  "Virtual Reality",
  "Bioinformatics",
  "Future of Work",
  "Quantum Computing",
  "Biomedical Innovations",
  "Urban Planning",
  "Augmented Reality",
  "Nanotechnology Applications",
  "Robotics in Healthcare",
  "Cognitive Neuroscience",
  "Cryptocurrency Trends",
  "Microbial Ecology",
  "Cognitive Computing",
  "Sustainable Agriculture",
  "3D Printing Technology",
  "Cryptographic Protocols",
  "Marine Biology Discoveries",
  "Social Media Influence",
  "Quantum Entanglement",
  "Autonomous Vehicles",
  "Green Architecture",
  "Renewable Energy Policy",
  "Global Health Initiatives",
  "Internet of Things (IoT)",
  "Space Tourism",
  "Human-Computer Interaction",
  "Future of Education",
  "Antibiotic Resistance",
  "Ethical Artificial Intelligence",
  "Behavioral Economics",
  "Wildlife Conservation",
  "Dark Matter Studies",
  "Cryptocurrency Regulations",
  "Quantum Teleportation",
  "Precision Medicine",
  "Oceanography Advances",
  "Cultural Heritage Preservation",
  "Fusion Energy Research",
  "Neurotechnology Developments",
  "Wearable Technology",
  "Green Urban Spaces",
  "Social Impact Investing",
  "Climate Action Strategies",
  "Planetary Science",
  "Quantum Cryptography",
  "Sustainable Fashion",
  "Data Privacy Laws",
  "Earth Observation Satellites",
  "Personalized Medicine",
  "Cognitive Robotics",
  "Cryptocurrency Adoption",
  "Environmental Ethics",
  "Space Debris Management",
  "Human-AI Collaboration",
  "Regenerative Medicine",
  "Smart Cities Initiatives",
  "Cybersecurity Measures",
  "Mental Health Technologies",
  "Green Transportation",
  "Renewable Energy Storage",
  "Augmented Human Intelligence",
  "Quantum Algorithms",
  "Precision Agriculture",
  "Digital Identity Security",
  "Ocean Renewable Energy",
  "Sustainable Tourism",
  "Biodegradable Materials",
  "Artificial General Intelligence",
  "Indigenous Knowledge Systems",
  "Future of Space Colonization",
  "Quantum Information Science",
  "Precision Health",
  "Sustainable retroculture",
  "Ethical Design in Technology",
  "Neuroplasticity Research",
  "Space Debris Cleanup",
  "Cryptocurrency Innovations",
  "Global Education Access",
  "Quantum Materials",
  "Cognitive Automation",
  "Precision Agriculture",
  "Sustainable Supply Chains",
  "AI in Creative Industries",
  "Digital Healthcare Revolution",
  "Quantum Sensors",
  "Sustainable Urban Mobility",
  "Ethical AI Governance"
];
export default topicsArray;